--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/SimpleJoinUI
build-by-default: true
branches:
- main
projects:
  SimpleJoinUI:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
    icon: icon.PNG
...
