# Made by Terpz710

# Messages Section
messages:
  # Title
  # The title displayed at the top of the form.
  title: "Welcome to the Server!"
  
  # Content
  # Content lines displayed in the form (each line is separated by a hyphen "-").
  # Add as many lines you need.
  content:
    - "Welcome {player}!"
    - "Follow fhe rules below!"
    - "Made by Terpz710"
  
  # Buttons
  # Button labels available in the form.
  buttons:
    - "ok"
    
  # Title on Click
  # Message displayed when the player clicks "ok"
  title_on_click: "Welcome!"
  
  # Subtitle Text
  # Subtitle text displayed when the player clicks "ok"
  subtitle_text: "Enjoy your stay {player}"

  # Must-Click-OK Message
  # Message displayed when the player tries to close the form without clicking "ok"
  must_click_ok_message: "You must click §eok§f to close the form."
